name: Publish Dev Build

on:
  push:
    tags:
      - 0.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: sudo apt-get install --yes git jq
    - run: npm install
    - run: npm run build
    - run: .github/scripts/publish-dev-build '${{ secrets.GITHUB_TOKEN }}'
